name: Build & Deploy pipeline with turbo repo

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Repository
        uses: actions/checkout@v3

      - name: Setup Node.js version 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node modules
        id: dependencies-cache
        uses: actions/cache@v3
        env:
          cache-name: node-modules
        with:
          path: ./node_modules/**
          key: ${{ runner.os }}-dependencies-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - if: ${{ steps.dependencies-cache.outputs.cache-hit != 'true' }}
        name: Reload the dependencies
        continue-on-error: true
        run: npm install

      - name: Cache build output
        id: build-cache
        uses: actions/cache@v3
        env:
          cache-name: turbo-cache
        with:
          path: ./node_modules/.cache/turbo/**
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Build
        run: npx turbo build:app build:json-prettify build:json-uglify

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: prettify-and-uglify-build
          path: build/**

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check Repository
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: prettify-and-uglify-build
          path: build

      # - name: Deploy to Netlify
      #   uses: nwtgck/actions-netlify@v2
      #   with:
      #     publish-dir: "./build"
      #     production-branch: main
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     deploy-message: "Deploy from GitHub Actions"
      #     enable-pull-request-comment: false
      #     enable-commit-comment: true
      #     overwrites-pull-request-comment: true
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #   timeout-minutes: 1
