name: Build & Deploy pipeline with turbo repo

on:
  push:
    branches: ["main"]

jobs:
  load-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node modules
        id: dependencies-cache
        uses: actions/cache@v3
        env:
          cache-name: node-modules
        with:
          path: ./node_modules/**
          key: ${{ runner.os }}-dependencies-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - if: ${{ steps.dependencies-cache.outputs.cache-hit != 'true' }}
        name: Reload the dependencies
        continue-on-error: true
        run: npm install

  build-app:
    needs: load-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Load dependencies
        id: dependencies-cache
        uses: actions/cache@v3
        env:
          cache-name: node-modules
        with:
          path: ./node_modules/**
          key: ${{ runner.os }}-dependencies-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Load build cache
        id: build-cache
        uses: actions/cache@v3
        env:
          cache-name: app
        with:
          path: ./node_modules/.cache/turbo/**
          key: ${{ runner.os }}-build-cache-${{ env.cache-name }}-${{ hashFiles('src/**') }}

      - name: Build
        run: npx turbo build:app

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: prettify-and-uglify-app-build
          path: build/**

  build-json-prettify:
    needs: load-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Load dependencies
        id: dependencies-cache
        uses: actions/cache@v3
        env:
          cache-name: node-modules
        with:
          path: ./node_modules/**
          key: ${{ runner.os }}-dependencies-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Load build cache
        id: build-cache
        uses: actions/cache@v3
        env:
          cache-name: json-prettify
        with:
          path: ./node_modules/.cache/turbo/**
          key: ${{ runner.os }}-build-cache-${{ env.cache-name }}-${{ hashFiles('json-prettify/**') }}

      - if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
        name: Delete old build cache
        run: |
          key=$(curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/deshmukhakash55/prettify-and-uglify/actions/caches | jq '.actions_caches' | jq '.[].key' | grep 'json-prettify')
          echo ${key}

      - name: Build
        run: npx turbo build:json-prettify

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: prettify-and-uglify-json-prettify-build
          path: build/**

  build-json-uglify:
    needs: load-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Load dependencies
        id: dependencies-cache
        uses: actions/cache@v3
        env:
          cache-name: node-modules
        with:
          path: ./node_modules/**
          key: ${{ runner.os }}-dependencies-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Load build cache
        id: build-cache
        uses: actions/cache@v3
        env:
          cache-name: json-uglify
        with:
          path: ./node_modules/.cache/turbo/**
          key: ${{ runner.os }}-build-cache-${{ env.cache-name }}-${{ hashFiles('json-uglify/**') }}

      - name: Build
        run: npx turbo build:json-uglify

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: prettify-and-uglify-json-uglify-build
          path: build/**

  deploy:
    needs: [build-app, build-json-prettify, build-json-uglify]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download App Artifacts
        uses: actions/download-artifact@v3
        with:
          name: prettify-and-uglify-app-build
          path: build

      - name: Download JSON Prettify Artifacts
        uses: actions/download-artifact@v3
        with:
          name: prettify-and-uglify-json-prettify-build
          path: build

      - name: Download JSON Uglify Artifacts
        uses: actions/download-artifact@v3
        with:
          name: prettify-and-uglify-json-uglify-build
          path: build

      # - name: Deploy to Netlify
      #   uses: nwtgck/actions-netlify@v2
      #   with:
      #     publish-dir: "./build"
      #     production-branch: main
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     deploy-message: "Deploy from GitHub Actions"
      #     enable-pull-request-comment: false
      #     enable-commit-comment: true
      #     overwrites-pull-request-comment: true
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #   timeout-minutes: 1
